sudo: false

language: go

go:
  - 1.4

services:
  - redis-server

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

env:
  - REDIS_HOST=localhost REDIS_PORT=6379 REDIS_DB=1

install:
  - cp -rf $HOME/gopath/src/github.com/sharma-abhishek-it/fcompute $HOME/gopath/src/
  - cd $HOME/gopath/src/fcompute
  - go get ./...
  - cd $HOME/gopath/src/github.com/sharma-abhishek-it/fcompute

script:
  - $HOME/gopath/bin/goveralls -service=travis-ci ./...

notifications:
  email: false
